### ISSUE TITLE
Unable to Fulfill Bounty

### ISSUE THREAD

**Issue by scrapperbitch** [Polkadot-Network/hello-world-by-polkadot#21]
When i try to submitted the second work  I got notify "Unable to fullfill Bounty. Please try again later"on Gitcoin. It's almost 24 Hours :( and cuz this is my first bounty that i ever follow on the gitcoin and i don't knw what to do to fixed this. Pls help!
![unable_to fulfill bounty](https://user-images.githubusercontent.com/71956576/96299412-3b9adc00-101e-11eb-8a96-48e7bc03efc9.png)

**Comment by NukeManDan** [comment]
@scrapperbitch I am betting you get what I get and reported to gitcoin here: https://github.com/gitcoinco/web/issues/7695

Take a look at the console (crtl+shit+k) and look for errors there in the log. Likely related to the fields not being completed right.

**Comment by octavioamu** [comment]
should be fixed now please let me know if you find problems again.

**Comment by scrapperbitch** [comment]
nah man, seriously!
idk .. i just dang it.
anythin goes fine when i make an another account w/ sweety nickname LMAO.
Just closed! thx for your response guys
